/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listtask;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

/**
 *
 * @author Turab Bajeer
 */
public class ListFrame extends javax.swing.JFrame {

    /**
     * Creates new form ListFrame
     */
    
    static int item;
    DefaultListModel<String> listModel1 = new DefaultListModel<>();
    DefaultListModel<String> listModel2 = new DefaultListModel<>();
    public ListFrame() {
        initComponents();
        fillList1();
        fillList2();
        listModel1.addElement("Banana");
        listModel1.addElement("Apple");
        listModel1.addElement("Watemelon");
        listModel1.addElement("Grapes");
        listModel1.addElement("Orange");
        listModel1.addElement("Cucumber");
        listModel1.addElement("Eggplant");
        listModel1.addElement("Garlic");
        listModel1.addElement("GrapeFruit");
        
         listModel2.addElement("Green Beans");
         listModel2.addElement("Lemons");
         listModel2.addElement("Limes");
         listModel2.addElement("Onion");
         listModel2.addElement("Orange");
         listModel2.addElement("Cucumber");
         listModel2.addElement("Potato");
         listModel2.addElement("Tomato");
         listModel2.addElement("Lady Finger");
         
         setLocation(300, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list1 = new javax.swing.JList<>();
        shiftAllLeftButton = new javax.swing.JButton();
        shiftOneRightButton = new javax.swing.JButton();
        shiftOneLeftButton = new javax.swing.JButton();
        shiftAllRightButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Green Beans", "Lemons", "Limes", "Onion", "Oranges", "Potato", "Tomato", "Lady Finger", "Beans" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list2);

        list1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Banana", "Apple", "Watemelon", "Grapes", "Orange", "Cucumber", "Eggplant", "Garlic", "GrapeFruit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(list1);

        shiftAllLeftButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shiftAllLeftButton.setText("<<");
        shiftAllLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftAllLeftButtonActionPerformed(evt);
            }
        });

        shiftOneRightButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shiftOneRightButton.setText(">");
        shiftOneRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftOneRightButtonActionPerformed(evt);
            }
        });

        shiftOneLeftButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shiftOneLeftButton.setText("<");
        shiftOneLeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftOneLeftButtonActionPerformed(evt);
            }
        });

        shiftAllRightButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        shiftAllRightButton.setText(">>");
        shiftAllRightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shiftAllRightButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shiftAllRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shiftOneLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shiftAllLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shiftOneRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(shiftOneRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(shiftOneLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(shiftAllRightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(shiftAllLeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shiftOneRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftOneRightButtonActionPerformed
       //int item = list1.getSelectedIndex();
       // System.out.println("item "+item);
       if(item != -1){
            listModel2.addElement(listModel1.getElementAt(item));
            listModel1.remove(item);
            
            list1.setModel(listModel1);
            list2.setModel(listModel2);
       }
    }//GEN-LAST:event_shiftOneRightButtonActionPerformed

    private void list1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list1MouseClicked
       item = list1.getSelectedIndex();
        
    }//GEN-LAST:event_list1MouseClicked

    private void shiftOneLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftOneLeftButtonActionPerformed
       if(item != -1){
            listModel1.addElement(listModel2.getElementAt(item));
            listModel2.remove(item);
            
            list1.setModel(listModel1);
            list2.setModel(listModel2);
       }
    }//GEN-LAST:event_shiftOneLeftButtonActionPerformed

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
         item = list2.getSelectedIndex();
    }//GEN-LAST:event_list2MouseClicked

    private void shiftAllRightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftAllRightButtonActionPerformed
        shiftAllFromList1toList2();
       
    }//GEN-LAST:event_shiftAllRightButtonActionPerformed

    private void shiftAllLeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftAllLeftButtonActionPerformed
       shiftAllFromList2toList1();
    }//GEN-LAST:event_shiftAllLeftButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListFrame().setVisible(true);
            }
        });
    }
    
    
    public void fillList1(){
      
    
        list1.setModel(listModel1);
        
    }
    
    public void fillList2(){
       
         list2.setModel(listModel2);

    }
    
    public void shiftAllFromList1toList2(){
        int size = listModel1.getSize();
       for(int i=0; i< size; i++){
            listModel2.addElement(listModel1.get(i));
         
        }
        listModel1.removeAllElements();
        list1.setModel(listModel1);
        list2.setModel(listModel2);
    }
    
    public void shiftAllFromList2toList1(){
        int size = listModel2.getSize();
       for(int i=0; i< size; i++){
            listModel1.addElement(listModel2.get(i));
         
        }
        listModel2.removeAllElements();
        list1.setModel(listModel1);
        list2.setModel(listModel2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> list1;
    private javax.swing.JList<String> list2;
    private javax.swing.JButton shiftAllLeftButton;
    private javax.swing.JButton shiftAllRightButton;
    private javax.swing.JButton shiftOneLeftButton;
    private javax.swing.JButton shiftOneRightButton;
    // End of variables declaration//GEN-END:variables
}
